name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the Repository.
      uses: actions/checkout@v3
    - name: Use Node.js18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install project dependencies.
      run: npm install
    - name: Run unit tests for the App.
      run: npm run test:unit
    - name: Display my SoftUni username
      run: echo "ZhivkoTringov"
